#!/usr/bin/env bun

/**
 * Generate _redirects File
 *
 * Generates the public/_redirects file from:
 * 1. Product JSON files (gumroadProductSlugs -> /product/{id} redirects)
 * 2. src/data/redirects.json (additional redirects like /affiliates and SPA fallback)
 *
 * Usage:
 *   bun run generate:redirects
 *   bun scripts/generate-redirects.ts
 *
 * Exit codes:
 *   0 - Generation successful
 *   1 - Generation failed
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs'
import { resolve, dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { RedirectsFileSchema, type RedirectEntry } from '../src/schemas/redirect.schema.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// File paths
const PRODUCTS_DIR = resolve(__dirname, '../src/data/products')
const REDIRECTS_JSON = resolve(__dirname, '../src/data/redirects.json')
const OUTPUT_FILE = resolve(__dirname, '../public/_redirects')

/**
 * Load product Gumroad slugs from product JSON files
 */
function loadProductSlugs(): Map<string, string[]> {
    const productSlugs = new Map<string, string[]>()
    const files = readdirSync(PRODUCTS_DIR)

    // Match only main product files
    const productFiles = files.filter((f) => {
        if (!f.endsWith('.json')) return false
        if (
            f.includes('-faq.json') ||
            f.includes('-media.json') ||
            f.includes('-sales-copy-') ||
            f.includes('-stats.json') ||
            f.includes('-testimonials.json')
        ) {
            return false
        }
        return true
    })

    for (const file of productFiles) {
        const filePath = join(PRODUCTS_DIR, file)
        try {
            const content = readFileSync(filePath, 'utf-8')
            const parsed = JSON.parse(content)

            // Only include products with gumroadProductSlugs
            if (parsed.gumroadProductSlugs && Array.isArray(parsed.gumroadProductSlugs)) {
                productSlugs.set(parsed.id, parsed.gumroadProductSlugs)
            }
        } catch (error) {
            console.error(`  Failed to parse ${file}: ${error}`)
        }
    }

    return productSlugs
}

/**
 * Load additional redirects from redirects.json
 */
function loadAdditionalRedirects(): RedirectEntry[] {
    if (!existsSync(REDIRECTS_JSON)) {
        console.warn(`  Warning: ${REDIRECTS_JSON} not found, skipping additional redirects`)
        return []
    }

    try {
        const content = readFileSync(REDIRECTS_JSON, 'utf-8')
        const parsed = JSON.parse(content)

        const validation = RedirectsFileSchema.safeParse(parsed)
        if (!validation.success) {
            console.error('  Invalid redirects.json:')
            validation.error.issues.forEach((err) => {
                console.error(`    - ${err.path.join('.')}: ${err.message}`)
            })
            throw new Error('Invalid redirects.json')
        }

        return validation.data.redirects
    } catch (error) {
        if (error instanceof SyntaxError) {
            throw new Error(`Failed to parse redirects.json: ${error.message}`)
        }
        throw error
    }
}

/**
 * Group product slugs by product ID for organized output
 */
function groupSlugsByProduct(
    productSlugs: Map<string, string[]>
): Array<{ productId: string; slugs: string[] }> {
    const result: Array<{ productId: string; slugs: string[] }> = []

    for (const [productId, slugs] of productSlugs.entries()) {
        if (slugs.length > 0) {
            result.push({ productId, slugs })
        }
    }

    // Sort by product ID for consistent output
    result.sort((a, b) => a.productId.localeCompare(b.productId))

    return result
}

/**
 * Generate the _redirects file content
 */
function generateRedirectsContent(
    productSlugs: Map<string, string[]>,
    additionalRedirects: RedirectEntry[]
): string {
    const lines: string[] = []

    // Header
    lines.push('')
    lines.push('# Redirects: From Gumroad /l/:product-slug to /product/:id')
    lines.push('# Auto-generated by scripts/generate-redirects.ts')
    lines.push('# DO NOT EDIT MANUALLY - changes will be overwritten')
    lines.push('')

    // Product redirects
    const groupedSlugs = groupSlugsByProduct(productSlugs)

    for (const { productId, slugs } of groupedSlugs) {
        lines.push(`## ${productId}`)
        for (const slug of slugs) {
            lines.push(`/l/${slug} /product/${productId} 301`)
        }
        lines.push('')
    }

    // Additional redirects
    if (additionalRedirects.length > 0) {
        lines.push('# Other redirects')
        for (const redirect of additionalRedirects) {
            // Skip the SPA fallback for now, we'll add it at the end
            if (redirect.source === '/*') continue
            lines.push(`${redirect.source} ${redirect.destination} ${redirect.httpStatusCode}`)
        }
        lines.push('')
    }

    // Note: SPA fallback (/* -> /index.html) is intentionally NOT included here.
    // Cloudflare Pages handles SPA routing automatically and including it causes
    // an infinite loop error during deployment.

    return lines.join('\n')
}

function main() {
    console.log('🔄 Generating _redirects file...\n')

    // Load product slugs
    console.log('📦 Loading product Gumroad slugs...')
    const productSlugs = loadProductSlugs()
    console.log(`   Found ${productSlugs.size} products with Gumroad slugs`)

    let totalSlugs = 0
    for (const slugs of productSlugs.values()) {
        totalSlugs += slugs.length
    }
    console.log(`   Total slugs: ${totalSlugs}\n`)

    // Load additional redirects
    console.log('📄 Loading additional redirects from redirects.json...')
    let additionalRedirects: RedirectEntry[] = []
    try {
        additionalRedirects = loadAdditionalRedirects()
        console.log(`   Found ${additionalRedirects.length} additional redirects\n`)
    } catch (error) {
        console.error(`❌ ${error}`)
        process.exit(1)
    }

    // Generate content
    console.log('✍️  Generating _redirects content...')
    const content = generateRedirectsContent(productSlugs, additionalRedirects)

    // Write output file
    try {
        writeFileSync(OUTPUT_FILE, content, 'utf-8')
        console.log(`\n✅ Successfully generated _redirects`)
        console.log(`📄 Output written to: ${OUTPUT_FILE}`)
        console.log(`   - Product redirects: ${totalSlugs}`)
        console.log(`   - Additional redirects: ${additionalRedirects.length}`)
        process.exit(0)
    } catch (error) {
        console.error(`\n❌ Failed to write _redirects: ${error}`)
        process.exit(1)
    }
}

// Run main function
main()
